version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db